version: 0.1
env:
    secrets-manager:
      TOKEN: sonarCloud:tokenForSonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=weikertsecurity_javaplayground -Dsonar.organization=weikertsecurity -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN